export const clientRoot = 'https://localhost:5002/'
export const stsAuthority = 'https://localhost:44342/'
export const clientId = 'code_flow_client_id'
export const credentialsClientId = 'credentials_client_id'
export const credentialsClientSecret = 'credentials_C1ient$ecret'
export const credentialsClientGrantType = 'client_credentials'
export const scope = 'openid profile api'
export const responseType = 'code'