export const clientRoot = 'https://localhost:5002/'
export const stsAuthority = 'https://localhost:44342/'
export const clientId = 'code_flow_client_id'
export const scope = 'openid profile api'
export const responseType = 'code'
